# Generated by Django 3.1.4 on 2021-01-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100, null=True)),
                ('student_teacher_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('CiNiHi', models.IntegerField(blank=True, default=0, null=True)),
                ('fte', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
