# Generated by Django 3.0.6 on 2020-11-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=200, null=True)),
                ('course_code', models.CharField(max_length=200, null=True)),
                ('course_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('programme', models.CharField(max_length=200, null=True)),
                ('session', models.DateField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
