# Generated by Django 3.0.6 on 2020-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
