# Generated by Django 3.1.4 on 2021-01-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0002_teachingload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingload',
            name='fte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
