# Generated by Django 3.1.4 on 2021-01-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0003_auto_20210126_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingload',
            old_name='fte',
            new_name='fte_semester',
        ),
        migrations.AddField(
            model_name='teachingload',
            name='fte_session',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='teachingload',
            name='workload',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
