# Generated by Django 3.0.6 on 2020-12-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0003_auto_20201126_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='fte',
            name='session',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
