# Generated by Django 3.0.6 on 2020-12-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0005_auto_20201203_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department_owner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
