# Generated by Django 3.1.4 on 2021-01-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0005_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_id',
            field=models.IntegerField(default=0, max_length=50, null=True),
        ),
    ]
