# Generated by Django 3.0.6 on 2020-12-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0006_student_department_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department_owner',
            new_name='owner',
        ),
    ]
