# Generated by Django 3.1.4 on 2021-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0007_teachingload_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='lecturer_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
