# Generated by Django 3.1.4 on 2021-01-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0007_auto_20201218_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme_for_courses',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='programme_student',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
