# Generated by Django 3.1.4 on 2021-01-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0008_auto_20210111_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='fte',
            name='CiNi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fte',
            name='l',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
