# Generated by Django 3.0.6 on 2021-01-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0008_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme_for_courses',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
