# Generated by Django 3.0.6 on 2021-01-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0009_student_programme_for_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme_student',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
