# Generated by Django 3.0.6 on 2021-01-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computation', '0010_student_programme_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programme_student',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
